### ISSUE TITLE
Add Flyway to handle database schema migration

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1098]
Currently, the backend is using typerom synchronize to true option to do database migration which is not ideal in production environments, so need to create a more robust pattern that should be production ready. Flyway seems to be a good candidate.

**Comment by DerekRoberts** [comment]
Agreed!  :)

**Comment by paulushcgcj** [comment]
On [old growth](https://github.com/bcgov/nr-old-growth) I used a similar approach, but instead of baking the migration inside flyway, I just added the migrations as part of a [config map](https://github.com/bcgov/nr-old-growth/blob/main/.github/openshift/deploy.backend.yml#LL66C3-L86C119). This way the [init container](https://github.com/bcgov/nr-old-growth/blob/main/.github/openshift/deploy.backend.yml#L142) is just a "template" and the migration will be tied to the application itself, making it easier to be copied/replicated by other projects.
